language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: rCQIIltD74rmzyVJnHOqUuiZ1pp4V/JrNMlNV8fZTjygC2DTOExBYFROqQFIn0sTceLMjWRt6NYAsCrAVdzD7ob42BW6uDTSojegcPhgKveMxd2sLdhzjUdts2JsAW4c/1PleVWJ3zurdOz7ZI9OQ24fe9r4VDd5mfuEwi6pwuF4wGZ5wsYDXJ7mCB3CST/epad7Y/F07fspTW205ht5rwMvppkOqKQGydX1B0vQj+v0O88RDKCe2Ae/vqPCyfLok/p4uY1M4oMnu8mi+HOipy53gyvtM3WB3s5oCWa1jEfTJ3TeBYfwDy/NleUdDgp+DtSAwwrSKTYDDfuNbs19FuP1ZoK+NAI6JwHE9Ou/8edZjwr3mzk8gBKv99T9SM9PRN3e6CgvVJQ82IAC16BwhnpsIGONLOlonObhdQCbMsWFesSZ9cB0iS2Vx+JWmn/JlO2IloxdVsDAowQX6E8jLXK+mEaQjfg3oY8MbEYDX9o5Aqh6ks5duyy7ftH1bLFpR95/MNcCnifqt2U1bWpx074O9gQr59q99S0h95e97vw32DEHbEiCwx6Jff1HU846EkVPJCHpyqI01M/99LqukhvCdVRy/DIfyD25kb+7iF7dWI+XJIV6pi3HFJnA600Sdk2JD/27OvaZ7HZIsgN1mw6pw4cnouT7QuRwhNyx20U=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
